### ISSUE TITLE
your readme file needs more love

### ISSUE THREAD

**Issue by alvarouribe** [ethanresnick/json-api-example#10]
Hey man your readme file says - `POST http://localhost:3000/schools` to add a school
Can you put an example I am using Postman but I can get it right !

first it says 
{"errors":[{"status":"415","title":"Invalid Media Type","detail":"The request's Content-Type must be application/vnd.api+json, but you provided text/plain."}]}

Then I add that and it says 
{"errors":[{"status":"400","title":"The resources you provided could not be parsed.","detail":"The precise error was: \"type is required\"."}]}

in my body I have this:
{ "data": 
    [{
    "name": "De La Salle",
    "description": "De La Salle School"
    }]
}

Why making it so hard man??  just add a curl example so you don't get people frustrated using your code

**Comment by ethanresnick** [comment]
First, to your concrete question, the body should be:

```
{
   "data": {
      "type": "schools",
      "name": "De La Salle",
      "description": "De La Salle School"
   }
}
```

Like the error was saying, you needed a `type` key in your resource object. This is a basic JSON:API requirement.

To your point more generally, the readme could definitely use some love. I'm really busy right now, but I'd gladly accept a PR.
