### ISSUE TITLE
Missing a lot of dependencies while installing

### ISSUE THREAD

**Issue by adriaandotcom** [ethanresnick/json-api-example#2]
When running `npm install` it installs with some warnings

```
imac:~/Developer/json-api-example$ npm install
npm WARN deprecated gulp-clean@0.2.4: use gulp-rimraf instead
^C
imac:~/Developer/json-api-example$ npm install
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/express-simple-router requires path-to-regexp@'^0.2.1' but will load
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/path-to-regexp,
npm WARN unmet dependency which is version 0.1.2
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/express-simple-router requires q@'1.1.x' but will load
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/q,
npm WARN unmet dependency which is version 1.4.1
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/json-api requires pluralize@'0.0.11' but will load
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/pluralize,
npm WARN unmet dependency which is version 0.0.10
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/gulp requires gulp-util@'^3.0.0' but will load
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/gulp-util,
npm WARN unmet dependency which is version 2.2.20
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/gulp-jshint requires gulp-util@'^3.0.0' but will load
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/gulp-util,
npm WARN unmet dependency which is version 2.2.20
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/gulp-replace requires event-stream@'~3.0.18' but will load
npm WARN unmet dependency /Users/imac/Developer/json-api-example/node_modules/event-stream,
npm WARN unmet dependency which is version 3.1.7
```

And then it shows a lot of missing modules errors while running `node src/index.js`:
- Error: Cannot find module 'utils-merge'
- Error: Cannot find module 'escape-html'
- Error: Cannot find module 'debug'
- ...

**Comment by ethanresnick** [comment]
I can't tell for sure, but I _think_ you may have accidentally stopped the install before it was finished (with the `^C`), so now there are folders for all these dependencies in your `node_modules` folder but the dependencies themselves aren't completely installed (i.e. the dependencies of the dependencies haven't been downloaded etc). 

I'd try deleting the `node_modules` folder, maybe running from `npm cache clean` and then running `npm install` again. If you still have issues after that, I'll try again to reproduce this issue on my machine so we can fix it. The quick attempt I made to reproduce it so far though didn't show this problem.

**Comment by adriaandotcom** [comment]
> I think you may have accidentally stopped the install before it was finished (with the ^C)

That looks like it indeed, will try it soon again, thanks!

**Edit:** it works now!
